#server:
#  port: 8181
#spring:
#  datasource:
#    url: jdbc:h2:file:C:\Users\SEBASTIAN\h2\basesita
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
##      ddl-auto: create
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
      #settings:
        #trace: false
        #web-allow-others: false
server:
  port: 8181
spring:
  application:
    name: demo-h2-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/beer_agency
    username: beer_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console